tables:
  test_table:
    validations:
      count_validation:
        source_table_name: test_table
        source: postgresql
        sourcequery: SELECT COUNT(*) FROM test_table
        target_table_name: test_table
        target: postgresql
        targetquery: SELECT COUNT(*) FROM test_table
