tables:
  test_001:
    validations:
      data_validation:
        source_table_name: test_001
        source: mssql
        source_database: migration_test
        source_schema: dbo
        sourcequery: SELECT COALESCE(CAST(s.base_salary AS VARCHAR(MAX)), '<<NULL>>')
          AS salary_base, COALESCE(CAST(d.dept_name AS VARCHAR(MAX)), '<<NULL>>')
          AS department, COALESCE(CAST(d.budget AS VARCHAR(MAX)), '<<NULL>>') AS budget,
          COALESCE(CAST(e.first_name AS VARCHAR(MAX)), '<<NULL>>') AS first_name,
          COALESCE(CAST(e.last_name AS VARCHAR(MAX)), '<<NULL>>') AS last_name FROM
          dbo.salaries AS s JOIN dbo.employees AS e ON s.employee_id = e.employee_id
          JOIN dbo.departments AS d ON e.dept_id = d.dept_id;
        target_table_name: test_001
        target: snowflake
        target_database: MIGRATION_TEST
        target_schema: PUBLIC
        targetquery: SELECT COALESCE(CAST(E.FIRST_NAME AS STRING), '<<NULL>>') AS
          FIRST_NAME, COALESCE(CAST(E.LAST_NAME AS STRING), '<<NULL>>') AS LAST_NAME,
          COALESCE(CAST(D.DEPT_NAME AS STRING), '<<NULL>>') AS DEPARTMENT, COALESCE(CAST(D.BUDGET
          AS STRING), '<<NULL>>') AS BUDGET, COALESCE(CAST(S.BASE_SALARY AS STRING),
          '<<NULL>>') AS BASE_SALARY FROM PUBLIC.EMPLOYEES E LEFT JOIN PUBLIC.DEPARTMENTS
          D ON E.DEPT_ID = D.DEPT_ID LEFT JOIN PUBLIC.SALARIES S ON E.EMPLOYEE_ID
          = S.EMPLOYEE_ID;
        pksourcecolumn: row_hash
        pktargetcolumn: row_hash
